### ISSUE TITLE
Memory configuration hardcoded at 512MB DDR3

### ISSUE THREAD

**Issue by hno** [linux-sunxi/u-boot-sunxi#1]
The u-boot spl loader currently have a hardcoded memory configuration of 512MB DDR3 at some fixed speed. Needs to either parameterize the DRAM settings somehow, or extend the code to probe for common configurations.

This involves both configuring the SDRAM controller proper, and to pass correct memory region information to the kernel on bootm.

**Comment by amery** [comment]
you mentioned spl could boot linux directly, that means reading fat. which also means it could load script.bin... and so parse the dram data out of it. no?

example from the mele a1000.

``` ini
[dram_para]
dram_baseaddr   = 0x40000000
dram_clk    = 360
dram_type   = 3
dram_rank_num   = 1
dram_chip_density   = 2048
dram_io_width   = 16
dram_bus_width  = 32
dram_cas    = 6
dram_zq = 0x7b
dram_odt_en = 0
dram_size   = 512
dram_tpr0   = 0x30926692
dram_tpr1   = 0x1090
dram_tpr2   = 0x1a0c8
dram_tpr3   = 0x0
dram_tpr4   = 0x0
dram_tpr5   = 0x0
dram_emr1   = 0x0
dram_emr2   = 0x0
dram_emr3   = 0x0
```

**Comment by hno** [comment]
fre 2012-05-25 klockan 13:48 -0700 skrev Alejandro Mery:

> you mentioned spl could boot linux directly, that means reading fat. which also means it could load script.bin... and so parse the dram data out of it. no?

spl could be made to read fat partitions.

it may be possible to add script.bin parsing as well, but memory is very
limited (24K) and I doubt it will all fit including script.bin.

In allwinner original bootloader the DRAM settings and a couple of other
parameters is stored in the header of boot0 (similar to spl).

Regards
Henrik

**Comment by hipboi** [comment]
> spl could be made to read fat partitions.
> 
> it may be possible to add script.bin parsing as well, but memory is very
> limited (24K) and I doubt it will all fit including script.bin.
> yes, i have tried. The spl will be bigger than 24K if fat is enabled.
> 
> In allwinner original bootloader the DRAM settings and a couple of other
> parameters is stored in the header of boot0 (similar to spl).

yes, the boot0 is handled by a pc program to get the right dram config from
script.bin.

One way to solve the problem is to try to get the real dram size by trying different paras, i will look into this.

**Comment by amery** [comment]
> One way to solve the problem is to try to get the real dram size by trying different paras, i will look into this.

you mean trial&error?

**Comment by hipboi** [comment]
yes, try to init dram for some times with different paras.

On Wed, May 30, 2012 at 4:03 PM, Alejandro Mery <
reply@reply.github.com

> wrote:
> 
> > One way to solve the problem is to try to get the real dram size by
> > trying different paras, i will look into this.
> 
> you mean trial&error?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hno/uboot-allwinner/issues/1#issuecomment-6004455

## 

Keep simple, stay foolish.

**Comment by hipboi** [comment]
only the following parameters is configurable usually.

``` ini
[dram_para]
dram_baseaddr   = 0x40000000
dram_clk    = 360
dram_type   = 3
dram_rank_num   = 1
dram_chip_density   = 2048
dram_io_width   = 16
dram_bus_width  = 32
dram_size   = 512
```

corresponding the following definition

```
#define DCR_TYPE_DDR2             (0)
#define DCR_TYPE_DDR3             (1)
#define DCR_IO_WIDTH_8            (1)
#define DCR_IO_WIDTH_16           (2)
#define DCR_CHIP_DENSITY_256Mb    (0)
#define DCR_CHIP_DENSITY_512Mb    (1)
#define DCR_CHIP_DENSITY_1Gb      (2)
#define DCR_CHIP_DENSITY_2Gb      (3)
#define DCR_CHIP_DENSITY_4Gb      (4)
#define DCR_CHIP_DENSITY_8Gb      (5)
#define DCR_BUS_WIDTH_16          (1)
#define DCR_BUS_WIDTH_32          (3)
#define DCR_ONE_RANK              (0)
#define DCR_TWO_RANKS             (1)
```

**Comment by hno** [comment]
Memory code has been reworked based on standby code, and is now parameterized with per board configuration.
