### ISSUE TITLE
u-boot fails to boot with Mele A1000

### ISSUE THREAD

**Issue by cnxsoft** [linux-sunxi/u-boot-sunxi#10]
This may be my mistake I don't see where I'm mistaken:

Here are the steps I follow to build u-boot

git clone https://github.com/hno/uboot-allwinner.git --depth=1
cd uboot-allwinner
make sun4i CROSS_COMPILE=arm-linux-gnueabihf- -j2

Then on a bootable SD card (meaning it can book linux), I copy spl and u-boot
dd if=spl/sun4i-spl.bin of=/dev/sdb bs=1024 seek=8
dd if=u-boot.bin of=/dev/sdb bs=1024 seek=32

If I use that image no data is apparently sent to the serial console.
If I only copy u-boot.bin (and not spl), it will just boot to android instead.

I build on Ubuntu 12.04 with the gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5).

**Comment by cnxsoft** [comment]
Some more tests:
I've tried another compiler:  https://sourcery.mentor.com/sgpp/lite/arm/portal/package8734/public/arm-none-eabi/arm-2011.03-42-arm-none-eabi-i686-pc-linux-gnu.tar.bz2, but the results remain the same.

The size of my sun4i-spl.bin is 15872 bytes, whereas the image at http://www.henriknordstrom.net/code/A10/hipboi-ubuntu-boot/uboot-spl.bin is 23552 bytes long.

**Comment by amery** [comment]
confirmed. Starting from a working SD card made out of http://www.henriknordstrom.net/code/A10/u-boot-mmc-hno-201203.img and then replacing the spl with a fresh one renders it card totally silent.

```
$ make sun4i CROSS_COMPILE=arm-linux-gnueabi-
$ sudo dd if=spl/sun4i-spl.bin of=/dev/sdb bs=1024 seek=8
[sudo] password for amery: 
16+0 records in
16+0 records out
16384 bytes (16 kB) copied, 0,95622 s, 17,1 kB/s
```

**Comment by amery** [comment]
`v2011.09-sun4i` works fine, the update to v2012.04.01 (+ both fixes, reverting boot.scr and fat support) breaks it.

**Comment by hno** [comment]
sunxi branch should work now.
