### ISSUE TITLE
error: no memory region specified for loadable section `.u_boot_cmd' 

### ISSUE THREAD

**Issue by sjau** [linux-sunxi/u-boot-sunxi#12]
I'm trying to cross-compile it on debian amd64 using this command:

make sun4i CROSS_COMPILE=arm-linux-gnueabi-

But I only get this error:

ty   -o /usr/local/src/uboot-allwinner/spl/lib/time.o time.c -c
arm-linux-gnueabi-gcc  -g  -Os   -fno-common -ffixed-r8 -msoft-float   -D__KERNEL__ -ffunction-sections -fdata-sections -DCONFIG_SYS_TEXT_BASE=0x4A000000 -DCONFIG_SPL_TEXT_BASE=0x0 -DCONFIG_SPL_BUILD -I/usr/local/src/uboot-allwinner/include -fno-builtin -ffreestanding -nostdinc -isystem /usr/lib/gcc/arm-linux-gnueabi/4.4.5/include -pipe  -DCONFIG_ARM -D__ARM__ -marm  -mabi=aapcs-linux -mno-thumb-interwork -march=armv5 -Wall -Wstrict-prototypes -fno-stack-protector -Wno-format-nonliteral -Wno-format-security   -o /usr/local/src/uboot-allwinner/spl/lib/vsprintf.o vsprintf.c -c
arm-linux-gnueabi-ld  -r -o /usr/local/src/uboot-allwinner/spl/lib/libgeneric.o  /usr/local/src/uboot-allwinner/spl/lib/ctype.o /usr/local/src/uboot-allwinner/spl/lib/div64.o /usr/local/src/uboot-allwinner/spl/lib/string.o /usr/local/src/uboot-allwinner/spl/lib/time.o /usr/local/src/uboot-allwinner/spl/lib/vsprintf.o
make[3]: Leaving directory `/usr/local/src/uboot-allwinner/lib'
arm-linux-gnueabi-gcc -E -g  -Os   -fno-common -ffixed-r8 -msoft-float   -D__KERNEL__ -ffunction-sections -fdata-sections -DCONFIG_SYS_TEXT_BASE=0x4A000000 -DCONFIG_SPL_TEXT_BASE=0x0 -DCONFIG_SPL_BUILD -I/usr/local/src/uboot-allwinner/include -fno-builtin -ffreestanding -nostdinc -isystem /usr/lib/gcc/arm-linux-gnueabi/4.4.5/include -pipe  -DCONFIG_ARM -D__ARM__ -marm  -mabi=aapcs-linux -mno-thumb-interwork -march=armv5 -include /usr/local/src/uboot-allwinner/include/u-boot/u-boot.lds.h -include /usr/local/src/uboot-allwinner/include/config.h  -ansi -D__ASSEMBLY__ -P - < /usr/local/src/uboot-allwinner/arch/arm/cpu/armv7/sunxi/u-boot-spl.lds > /usr/local/src/uboot-allwinner/spl/u-boot-spl.lds
UNDEF_SYM=`arm-linux-gnueabi-objdump -x /usr/local/src/uboot-allwinner/spl/arch/arm/cpu/armv7/libarmv7.o /usr/local/src/uboot-allwinner/spl/arch/arm/cpu/armv7/sunxi/libsunxi.o /usr/local/src/uboot-allwinner/spl/arch/arm/lib/libarm.o /usr/local/src/uboot-allwinner/spl/board/allwinner/a10-evb/liba10-evb.o /usr/local/src/uboot-allwinner/spl/common/libcommon.o /usr/local/src/uboot-allwinner/spl/disk/libdisk.o /usr/local/src/uboot-allwinner/spl/drivers/mmc/libmmc.o /usr/local/src/uboot-allwinner/spl/drivers/serial/libserial.o /usr/local/src/uboot-allwinner/spl/lib/libgeneric.o | sed  -n -e 's/._(__u_boot_cmd_._)/-u\1/p'|sort|uniq`; cd /usr/local/src/uboot-allwinner/spl/ && arm-linux-gnueabi-ld  -T /usr/local/src/uboot-allwinner/spl/u-boot-spl.lds --gc-sections -Bstatic -Ttext 0x0 $UNDEF_SYM arch/arm/cpu/armv7/start.o --start-group arch/arm/cpu/armv7/libarmv7.o arch/arm/cpu/armv7/sunxi/libsunxi.o arch/arm/lib/libarm.o board/allwinner/a10-evb/liba10-evb.o common/libcommon.o disk/libdisk.o drivers/mmc/libmmc.o drivers/serial/libserial.o lib/libgeneric.o --end-group /usr/local/src/uboot-allwinner/spl/arch/arm/lib/eabi_compat.o -L /usr/lib/gcc/arm-linux-gnueabi/4.4.5 -lgcc -L /usr/lib/gcc/arm-linux-gnueabi/4.4.5 -lgcc -Map u-boot-spl.map -o u-boot-spl
arm-linux-gnueabi-ld: error: no memory region specified for loadable section`.u_boot_cmd'
make[2]: **\* [/usr/local/src/uboot-allwinner/spl/u-boot-spl] Error 1
make[2]: Leaving directory `/usr/local/src/uboot-allwinner/spl'
make[1]: *** [spl/u-boot-spl.bin] Error 2
make[1]: Leaving directory`/usr/local/src/uboot-allwinner'
make: **\* [sun4i] Error 2

**Comment by hno** [comment]
lör 2012-06-30 klockan 03:27 -0700 skrev Stephan Jau:

> arm-linux-gnueabi-ld: error: no memory region specified for loadable section `.u_boot_cmd'

Thanks, I see where it's going wrong (watchdog command gets included in
SPL build for some reason). But wonder why my toolchain do not complain.
It should..

Regards
Henrik

**Comment by sjau** [comment]
Well, on git about a week ago it still worked fine.

**Comment by hno** [comment]
Fixed now.

**Comment by sjau** [comment]
Thx for the fix :) works just fine once more :)
