### ISSUE TITLE
Install to Nand flash

### ISSUE THREAD

**Issue by peica** [linux-sunxi/u-boot-sunxi#13]
Can I access the nand flash from u-boot and download it into the flash?

**Comment by hno** [comment]
lichee-dev branch has nand access. sun4i / lichee-dev-mmc branches do not.

nand driver will also be added to the sun4i branch with a bit cleanup.

**Comment by peica** [comment]
Oh, it sounds great. Thanks.

**Comment by peica** [comment]
Thanks for you remind. I am trying with lichee-dev. But do you mind to teach me how to download the bootloader into its nand? I refer some guides via Google, but them make me so confuse on it.

**Comment by hno** [comment]
lichee-dev only supports chainloading from allwinner boot0/boot1 bootloaders. See any ICS Android firmware for an example how it's done.

**Comment by M1cha** [comment]
Is it possible to implement both nand and mmc drivers?
This would be great so I could boot Android-Recovery(CWM) from SDcard to recovery my system.

**Comment by hno** [comment]
ons 2012-08-01 klockan 08:35 -0700 skrev M1cha:

> Is it possible to implement both nand and mmc drivers?

Yes.

> This would be great so I could boot Android-Recovery(CWM) from SDcard to recovery my system.

You don't need nand support in u-boot for that, only mmc. The kernel
nand driver manages nand access for recovery.

Regards
Henrik

**Comment by repvik** [comment]
Is there a timeframe on the nand merge? I'm considering looking into it, but I don't have a device with UART yet.

**Comment by hno** [comment]
lör 2012-08-11 klockan 03:41 -0700 skrev repvik:

> Is there a timeframe on the nand merge? I'm considering looking into
> it, but I don't have a device with UART yet. 

The NAND driver is merged in wip/explorenand. But we are still missing
access to the boot blocks, and there is also the issue about
straightening out the license header.

Regards
Henrik

**Comment by repvik** [comment]
What is the boot block access issue?

**Comment by hno** [comment]
lör 2012-08-11 klockan 05:57 -0700 skrev Tom Cubie:

> i will solve the license problem. 

Please clean up license headers in lichee-dev branch. We can inherit
them from there. The additions for SPL is already in a clean state.

Regards
Henrik

**Comment by maxnet** [comment]
> The NAND driver is merged in wip/explorenand.

Was wondering if it would be possible to boot the kernel/os from SD card with that, but load the script.bin with the hardware info from NAND?
Am interested in creating a generic Linux SD card image that would work on multiple a10 devices, instead of one that targets a specific device.

**Comment by hipboi** [comment]
On Wed, Sep 5, 2012 at 6:22 AM, maxnet notifications@github.com wrote:

>  The NAND driver is merged in wip/explorenand.
> 
> Was wondering if it would be possible to boot the kernel/os from SD card
> with that, but load the script.bin with the hardware info from NAND?
> Am interested in creating a generic Linux SD card image that would work on
> multiple a10 devices, instead of one that targets a specific device.
> 
> Actually this is a good idea. You can do that with what we have now. Use
> the u-boot spl from sun4i branch, and u-boot.bin from lichee-dev branch.
> u-boot in lichee-dev branch can load script.bin in nanda.
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/hno/uboot-allwinner/issues/13#issuecomment-8281231.

## 

Keep simple, stay foolish.

**Comment by maxnet** [comment]
> Actually this is a good idea. You can do that with what we have now. Use
> the u-boot spl from sun4i branch, and u-boot.bin from lichee-dev branch.
> u-boot in lichee-dev branch can load script.bin in nanda.

Do I need to do anything special to get the SPL to launch the lichee-dev u-boot?
They do not seem to get along:

```
U-Boot SPL 2011.09-00001-g922ca53 (Sep 15 2012 - 12:11:36)                        
MMC:   SUNXI SD/MMC: 0                                                            
Loading U-Boot...   OK!
Jumping to U-Boot...

U-Boot SPL 2011.09-00001-g922ca53 (Sep 15 2012 - 12:11:36)
MMC:   SUNXI SD/MMC: 0
Loading U-Boot...   OK!
Jumping to U-Boot...

U-Boot SPL 2011.09-00001-g922ca53 (Sep 15 2012 - 12:11:36)
MMC:   SUNXI SD/MMC: 0
Loading U-Boot...   OK!
Jumping to U-Boot...
```

What I did was:

```
git clone git://github.com/hno/uboot-allwinner.git --depth=1
cd uboot-allwinner
git checkout lichee/lichee-dev
make sun4i CROSS_COMPILE=arm-linux-gnueabihf-
sudo dd if=u-boot.bin of=/dev/sdd bs=1024 seek=32
```

(Where /dev/sdd is a SD card that already had the sun4i branch SPL, and a Linux OS on it)

**Comment by hno** [comment]
SPL should be able to start lichee-dev u-boot. But I have never tried.

**Comment by s1a1g1e1r1t** [comment]
Online linux-sunxi. org is the theme of boot card but I do not really understand
