### ISSUE TITLE
Unable to build sun5i branch

### ISSUE THREAD

**Issue by ghost** [linux-sunxi/u-boot-sunxi#14]
I was unable to build uboot for Allwinner A13. 

/home/willing/Android/cyanogenmod9/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-gcc  -g  -Os   -fno-common -ffixed-r8 -msoft-float   -D__KERNEL__ -DCONFIG_SYS_TEXT_BASE=0x4A000000 -DCONFIG_SPL_TEXT_BASE=0x30 -I/home/willing/git/uboot-allwinner/include -fno-builtin -ffreestanding -nostdinc -isystem /home/willing/Android/cyanogenmod9/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/include -pipe  -DCONFIG_ARM -D__ARM__ -marm  -mabi=aapcs-linux -mno-thumb-interwork -march=armv5 -Wall -Wstrict-prototypes -fno-stack-protector -Wno-format-nonliteral -Wno-format-security   -o timer.o timer.c -c
/home/willing/Android/cyanogenmod9/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-gcc  -g  -Os   -fno-common -ffixed-r8 -msoft-float   -D__KERNEL__ -DCONFIG_SYS_TEXT_BASE=0x4A000000 -DCONFIG_SPL_TEXT_BASE=0x30 -I/home/willing/git/uboot-allwinner/include -fno-builtin -ffreestanding -nostdinc -isystem /home/willing/Android/cyanogenmod9/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/include -pipe  -DCONFIG_ARM -D__ARM__ -marm  -mabi=aapcs-linux -mno-thumb-interwork -march=armv5 -Wall -Wstrict-prototypes -fno-stack-protector -Wno-format-nonliteral -Wno-format-security   -o dram.o dram.c -c
dram.c:37: error: redefinition of typedef '__u32'
/home/willing/git/uboot-allwinner/include/asm/types.h:18: note: previous declaration of '__u32' was here
dram.c:38: error: redefinition of typedef '__s32'
/home/willing/git/uboot-allwinner/include/asm/types.h:17: note: previous declaration of '__s32' was here
make[2]: **\* [dram.o] Error 1
make[2]: Opuszczenie katalogu `/home/willing/git/uboot-allwinner/arch/arm/cpu/armv7/sunxi'
make[1]: *** [arch/arm/cpu/armv7/sunxi/libsunxi.o] Error 2
make[1]: Opuszczenie katalogu`/home/willing/git/uboot-allwinner'
make: **\* [sun4i] Error 2
[willing@Willing-Cybrix-PC uboot-allwinner]$ make sunxi CROSS_COMPILE=/home/willing/Android/cyanogenmod9/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-
make: **\* No rule to make `sunxi'. Stop.

**Comment by hno** [comment]
ons 2012-09-12 klockan 07:00 -0700 skrev WillingMagic:

> dram.c:37: error: redefinition of typedef 'u32'
> dram.c:38: error: redefinition of typedef 's32'

It's ok to delete these two lines from dram.c.

The tree is currently undergoing migration into a shared and up to date
sunxi branch. At the moment the problem should exist there as well as
sun5i still uses that same dram.c which is in dare need of cleanup
(brute-forced into uboot from kernel source + changes).

Regards
Henrik

**Comment by ghost** [comment]
Ok, I'm rewriting rewrite of sunxi kernel, so I seek for solution for easy testing of kernel, because flashing every time with livesuit, it's not best solution.
