### ISSUE TITLE
fix lichee-dev (nand) to let us use linux without boot hacks

### ISSUE THREAD

**Issue by amery** [linux-sunxi/u-boot-sunxi#19]
even when the goal is obviously to let spl mature, mainlineing and been able to replace boot0/boot1 with free software it should be possible to slightly improve `lichee-dev` to pass the machine type registers and proper atag_mem info using the allwinner hack, and so allow people to boot from a mostly free boot chain from their NANDs with a simple drop in replacement for nanda's `linux/u-boot.bin` built from public sources.

**Comment by hno** [comment]
lichee-dev branch.
