### ISSUE TITLE
wiki corrections?

### ISSUE THREAD

**Issue by garycramblitt** [linux-sunxi/u-boot-sunxi#2]
I'm a newbee at this, but it looks to me like the build instructions on the wiki should be:

<code>
make sun4i CROSS_COMPILE=arm-linux-gnueabi-
dd if=spl/sunxi-spl.bin of=/dev/sdc bs=1024 seek=8
dd if=uboot.bin of=/dev/sdc bs=1024 seek=32
</code>
- Line 1: remove "-none"
- Line 2: sun4i -> sunxi

When I tried to build with arm-none-linux-gnueabi-gcc, I got /bin/bash: arm-none-linux-gnueabi-gcc: command not found.

Regards

**Comment by hno** [comment]
The 'CROSS_COMPILE value depends on your toolchain.

**Comment by hno** [comment]
Fixed.
