### ISSUE TITLE
The evb.bin is the default and not script.bin

### ISSUE THREAD

**Issue by ecanuto** [linux-sunxi/u-boot-sunxi#22]
According to the wiki "If no boot.scr is found then it will fall back to load script.bin & kernel uImage from the first partition in FAT format".

Here, using Rikomagic 802-II,  when I don't have any boot.src it loads "evb.bin" instead of "script.bin". I just figure it now because have been created a sd card that did not work until copy script.bin to evb.bin.

Is it the default behavior? Do we need to fix wiki or u-boot?

Cheers

**Comment by hno** [comment]
mån 2012-12-10 klockan 16:14 -0800 skrev Everaldo Canuto:

> According to the wiki "If no boot.scr is found then it will fall back
> to load script.bin & kernel uImage from the first partition in FAT
> format".

Yes. Or ext2/3.

> Here, using Rikomagic 802-II, when I don't have any boot.src it loads
> "evb.bin" instead of "script.bin". I just figure it now because have
> been created a sd card that did not work until copy script.bin to
> evb.bin.

Then you most likely have a saved environment with different settings
than the default, or are not using linux-sunxi u-boot.

> Is it the default behavior? Do we need to fix wiki or u-boot?

It's your installation that needs fixing.

Regards
Henrik
