### ISSUE TITLE
U-Boot does not read the uEnv.txt from SD automatically

### ISSUE THREAD

**Issue by vladsol** [linux-sunxi/u-boot-sunxi#28]
Hello!

I have a small problem, the U-Boot does not read uEnv.txt from fat partition on SDcard when booting:

U-Boot SPL 2013.01-05972-gd80f33a (Apr 01 2013 - 12:32:39)
Board: Cubieboard
DRAM: 1024MB
SUNXI SD/MMC: 0

U-Boot 2013.01-05972-gd80f33a (Apr 01 2013 - 12:32:39) Allwinner Technology

CPU:   SUNXI Family
Board: Cubieboard
I2C:   ready
DRAM:  1 GiB
MMC:   SUNXI SD/MMC: 0
In:    serial
Out:   serial
Err:   serial
Net:   wemac
Hit any key to stop autoboot:  0
reading uEnv.txt
<b> **Unable to read file uEnv.txt</b>

<b>At this time the "bootenv" variable is set:</b>
sun4i#printenv bootenv loadbootenv
bootenv=uEnv.txt
loadbootenv=fatload mmc 0 ${scriptaddr} ${bootenv} || ext2load mmc 0 ${scriptaddr} ${bootenv} || ext2load mmc 0 ${scriptaddr} boot/${bootenv}
sun4i#

<b>But!
When i manually set the bootenv variable, all is working:</b>

U-Boot 2013.01-05972-gd80f33a (Apr 01 2013 - 12:32:39) Allwinner Technology

CPU:   SUNXI Family
Board: Cubieboard
I2C:   ready
DRAM:  1 GiB
MMC:   SUNXI SD/MMC: 0
In:    serial
Out:   serial
Err:   serial
Net:   wemac
Hit any key to stop autoboot:  0
<b>sun4i#printenv bootenv loadbootenv</b>
bootenv=uEnv.txt
loadbootenv=fatload mmc 0 ${scriptaddr} ${bootenv} || ext2load mmc 0 ${scriptaddr} ${bootenv} || ext2load mmc 0 ${scriptaddr} boot/${bootenv}
<b>sun4i#run loadbootenv</b>
reading uEnv.txt
 *_Unable to read file uEnv.txt
Failed to mount ext2 filesystem...
*_ Unrecognized filesystem type **
Failed to mount ext2 filesystem...
*\* Unrecognized filesystem type **
<b>sun4i#setenv bootenv uEnv.txt
sun4i#run loadbootenv</b>
reading uEnv.txt
1172 bytes read in 7 ms (163.1 KiB/s)
sun4i#

**Comment by hno** [comment]
Make sure you do not have a saved environment. The uEnv.txt loading is defined in the default environment and a saved environment is likely to conflict.

**Comment by vladsol** [comment]
saved uEnv.txt and uEnv.txt on sdcard is same :-)
But... Why on "printenv" command i see the bootenv variable, but can't load it? :-)
"sun4i#run loadbootenv
reading uEnv.txt
**Unable to read file uEnv.txt"
But after "setenv bootenv uEnv.txt" all ok? :-) Nothing changed!

**Comment by hno** [comment]
saved environment is separate from uEnv.txt.

please try

  env -f -a
  saveenv
  reset

or clear the area on the sdcard where u-boot stores it's environment.

sön 2013-04-28 klockan 10:07 -0700 skrev vladsol:

**Comment by hno** [comment]
Tested & verified working just fine in sunxi-current branch. So I can only assume you had some saved environment that disturbs things.

**Comment by King-WJ** [comment]
Do you solve this problem ？

**Comment by King-WJ** [comment]
I also meet this problem，can you give me some advise?

**Comment by wens** [comment]
U-boot has been upstreamed. This fork is no longer developed or maintained, nor is this the proper place to report bugs against mainline U-boot. Please send bug reports to the U-boot mailing list.
