### ISSUE TITLE
Probable sunxi board.c syntaxe error

### ISSUE THREAD

**Issue by sysfwlab** [linux-sunxi/u-boot-sunxi#3]
Hello,
Hope i dont do a mistake, please check, but there is a potential mistake into function boot_from() from file board.c.

File : board.c - Fonction : boot_from()
Check for UNXI_GPF2_SDC0_CLK return SUNXI_BOOT_TYPE_MMC2 but this must be SUNXI_BOOT_TYPE_MMC0 no ?

Best regards
Bin

**Comment by hno** [comment]
Thanks, fixed
