### ISSUE TITLE
"sunxi-current" Branch Board Name

### ISSUE THREAD

**Issue by nvdl** [linux-sunxi/u-boot-sunxi#35]
In "sunxi-current" branch,

make a13-olinuxino ARCH=arm: Works

make a13_olinuxino ARCH=arm: Does not work

It is a bit inconsistent with the main branch, "sunxi", where "a13_olinuxino" works and "a13-olinuxino" does not.

**Comment by hno** [comment]
sön 2013-04-28 klockan 15:34 -0700 skrev Nvd:

> make a13-olinuxino ARCH=arm: Works
> 
> make a13_olinuxino ARCH=arm: Does not work
> 
> It is a bit inconsistent with the main branch.

yes board names have changed a bit in sunxi-current to more closely
match vendor product names. 

Regards
Henrik
