### ISSUE TITLE
A20 support please

### ISSUE THREAD

**Issue by cubieplayer** [linux-sunxi/u-boot-sunxi#37]
Thanks

**Comment by rzk** [comment]
I believe, the actual CubieBoard2 hardware did not get to linux-sunxi devs yet.
While this happens, you can look at lkcl work at his EOMA68 A20 board https://github.com/hno/u-boot/commits/lkcl-sunxi-a20 You should be able to do something with CONFIG_SUN7I setting.

Best Regards,
Dmitriy Beykun

**Comment by oliv3r** [comment]
Henrik has early support that appears to work quite well in his private repository: https://github.com/hno/u-boot/tree/wip/a20
And I have some experimental patches on top of that in my repository: https://github.com/oliv3r/u-boot-sunxi/tree/wip/a20

After vacation we will try merging those into sunxi-current.

**Comment by cubieplayer** [comment]
great
