### ISSUE TITLE
cubieboard2(A20) NAND capable uBoot 

### ISSUE THREAD

**Issue by cubieplayer** [linux-sunxi/u-boot-sunxi#41]
Is there any plan to support A20 boards such as cubieboard2 on NAND?

I tried to use the u-boot from lawrence http://www.cubieforums.com/index.php/topic,73.msg235.html#msg235
http://dl.cubieforums.com/loz/boot_partition/bootloader/cubie_nand_uboot_partition_image.bin

but without success the logging message is:

> HELLO! BOOT0 is starting!
> boot0 version : 2.0.0�
> read dram para.
> dram driver version: 1.14
> dram size =1024MB
> 0x00022822
> super_standby_flag = 0
> Succeed in opening nand flash.
> block from 2 to 6
> deal block 2
> Succeed in reading Boot1 file head.
> The size of Boot1 is 0x00068000.
> The file stored in 0x00000000 of block 2 is perfect.
> Check is correct.
> Ready to disable icache.
> Succeed in loading Boot1.
> Jump to Boot1.
> [       0.145] boot1 version : 2.0.0
> [       0.154] script installed early ok
> [       0.154] pmu type = 3
> [       0.156] bat vol = 0 mv
> [       0.172] axi:ahb:apb=4:2:2
> [       0.172] set dcdc2=1400mv, clock=912M successed
> [       0.174] key
> [       0.186] no key found
> [       0.186] flash init start
> [       0.186] NB1 : enter NFB_Init
> [       0.189] NB1 : enter phy init
> [       0.192] [NAND] nand driver(b) version: 0x0x00000002, 0x0x00000012, data: 0x20130325
> [       0.202] get the good blk ratio from hwscan : 944
> [       0.205] NB1 : nand phy init ok
> [       4.111] _RepairLogBlkTbl start
> [       4.115] Log Block Index 0x00000000, LogicBlockNum: 0x000000b9, LogBlockType: 0x00000000
> [       4.117] log0: 0x0000007b, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.124] datablock: 0x00000098, lastusedpage: 0x00000004
> [       4.132] Log Block Index 0x00000001, LogicBlockNum: 0x000000c8, LogBlockType: 0x00000000
> [       4.138] log0: 0x000000b0, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.145] datablock: 0x0000001a, lastusedpage: 0x00000079
> [       4.153] Log Block Index 0x00000002, LogicBlockNum: 0x00000013, LogBlockType: 0x00000000
> [       4.159] log0: 0x000000bd, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.165] datablock: 0x000000d8, lastusedpage: 0x00000033
> [       4.175] Log Block Index 0x00000003, LogicBlockNum: 0x000000c3, LogBlockType: 0x00000000
> [       4.179] log0: 0x0000008d, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.186] datablock: 0x000000e3, lastusedpage: 0x00000001
> [       4.195] Log Block Index 0x00000004, LogicBlockNum: 0x000000dc, LogBlockType: 0x00000000
> [       4.200] log0: 0x000000e2, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.207] datablock: 0x000003b6, lastusedpage: 0x00000001
> [       4.216] Log Block Index 0x00000005, LogicBlockNum: 0x000000c4, LogBlockType: 0x00000000
> [       4.221] log0: 0x0000008a, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.227] datablock: 0x0000074b, lastusedpage: 0x00000001
> [       4.236] Log Block Index 0x00000006, LogicBlockNum: 0x000000df, LogBlockType: 0x00000000
> [       4.241] log0: 0x000000cd, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.248] datablock: 0x0000074d, lastusedpage: 0x00000077
> [       4.256] Log Block Index 0x00000007, LogicBlockNum: 0x000000c0, LogBlockType: 0x00000000
> [       4.262] log0: 0x000000c4, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.268] datablock: 0x00000762, lastusedpage: 0x00000046
> [       4.278] Log Block Index 0x00000008, LogicBlockNum: 0x00000007, LogBlockType: 0x00000000
> [       4.282] log0: 0x00000774, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.289] datablock: 0x0000008c, lastusedpage: 0x00000003
> [       4.297] Log Block Index 0x00000009, LogicBlockNum: 0x00000008, LogBlockType: 0x00000000
> [       4.303] log0: 0x000000b4, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.310] datablock: 0x0000077d, lastusedpage: 0x00000075
> [       4.319] Log Block Index 0x0000000a, LogicBlockNum: 0x00000010, LogBlockType: 0x00000000
> [       4.324] log0: 0x000000bb, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.330] datablock: 0x0000077e, lastusedpage: 0x00000001
> [       4.339] Log Block Index 0x0000000b, LogicBlockNum: 0x000000c2, LogBlockType: 0x00000000
> [       4.344] log0: 0x000007b0, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.351] datablock: 0x000000c5, lastusedpage: 0x00000002
> [       4.537] datablock: 0x00000765, lastusedpage: 0x00000001
> [       4.546] Log Block Index 0x00000005, LogicBlockNum: 0x00000042, LogBlockType: 0x00000000
> [       4.551] log0: 0x00000766, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.557] datablock: 0x000003d5, lastusedpage: 0x00000009
> [       4.566] Log Block Index 0x00000006, LogicBlockNum: 0x00000033, LogBlockType: 0x00000000
> [       4.571] log0: 0x0000076a, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.578] datablock: 0x000003c6, lastusedpage: 0x0000001d
> [       4.587] Log Block Index 0x00000007, LogicBlockNum: 0x00000076, LogBlockType: 0x00000000
> [       4.592] log0: 0x00000776, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.598] datablock: 0x0000077b, lastusedpage: 0x00000007
> [       4.607] Log Block Index 0x00000008, LogicBlockNum: 0x00000032, LogBlockType: 0x00000000
> [       4.612] log0: 0x00000786, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.619] datablock: 0x00000761, lastusedpage: 0x0000003c
> [       4.627] Log Block Index 0x00000009, LogicBlockNum: 0x00000080, LogBlockType: 0x00000000
> [       4.633] log0: 0x0000079e, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.640] datablock: 0x0000079a, lastusedpage: 0x00000072
> [       4.649] Log Block Index 0x0000000a, LogicBlockNum: 0x00000075, LogBlockType: 0x00000000
> [       4.654] log0: 0x0000079c, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.660] datablock: 0x000007aa, lastusedpage: 0x00000004
> [       4.670] Log Block Index 0x0000000b, LogicBlockNum: 0x0000007d, LogBlockType: 0x00000000
> [       4.674] log0: 0x000007c2, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.681] datablock: 0x0000075d, lastusedpage: 0x00000001
> [       4.690] Log Block Index 0x0000000c, LogicBlockNum: 0x00000073, LogBlockType: 0x00000000
> [       4.695] log0: 0x000007ca, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.702] datablock: 0x000007ce, lastusedpage: 0x0000000a
> [       4.711] Log Block Index 0x0000000d, LogicBlockNum: 0x000002f2, LogBlockType: 0x00000000
> [       4.716] log0: 0x000007f2, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.722] datablock: 0x00000685, lastusedpage: 0x00000005
> [       4.731] Log Block Index 0x0000000e, LogicBlockNum: 0x00000272, LogBlockType: 0x00000000
> [       4.736] log0: 0x000007f6, Log1: 0x0000ffff, WriteIndex: 0x00000000
> [       4.743] datablock: 0x00000605, lastusedpage: 0x00000005
> [       4.748] _RepairLogBlkTbl end
> [       4.906] get mbr error
> [       4.906] NB1 : init ok
> [       4.906] flash init finish
> [       4.933] fs init fail
> [       4.933] fs init fail, jump to fel

**Comment by oliv3r** [comment]
Currently, we do not support any nand-capable u-boot. There is of course always the lychee branches for a10/a20 that do support nand, but those are allwinner sources and unsupported by us. Also very slowly is yuq's MTD work progressing which should add that in the future.

**Comment by cubieplayer** [comment]
Thank you
