### ISSUE TITLE
spl fails in uboot-2011.12 or later

### ISSUE THREAD

**Issue by hno** [linux-sunxi/u-boot-sunxi#5]
If the base uboot version if upgraded to 2011.12 or later then SPL shows no signt of life. Not even adding early uart output using uart0_puts works. It's as if the spl do not load but boot still stops on the mmc.

This is tracked in the wip/update branch

**Comment by hno** [comment]
Early ARM initialization code seems to have changed a bit doing a lot more magics with CP15.

<pre>
+ * (OMAP4 spl TEXT_BASE is not 32 byte aligned.
+ * Continue to use ROM code vector only in OMAP4 spl)
+ */
+#if !(defined(CONFIG_OMAP44XX) && defined(CONFIG_SPL_BUILD))
+       /* Set V=0 in CP15 SCTRL register - for VBAR to point to vector */
+       mrc     p15, 0, r0, c1, c0, 0   @ Read CP15 SCTRL Register
+       bic     r0, #CR_V               @ V = 0
+       mcr     p15, 0, r0, c1, c0, 0   @ Write CP15 SCTRL Register
+
+       /* Set vector address in CP15 VBAR register */
+       ldr     r0, =_start
+       mcr     p15, 0, r0, c12, c0, 0  @Set VBAR
 #endif
+#endif /* !Tegra2 */
+
        /* the mask ROM code should have PLL and others stable */
 #ifndef CONFIG_SKIP_LOWLEVEL_INIT
+       bl      cpu_init_cp15
        bl      cpu_init_crit
</pre>


cpu_init_cp15 was previously part of cppu_init_crit but is now split. Do not appear to be any code changes there other than the split in two functions.

**Comment by hno** [comment]
Yes it's this code being the culpit.

**Comment by hno** [comment]
Blocked this code on sun4i and it boots.

**Comment by hipboi** [comment]
is this issue solved? on the sun4i branch, the sun4i-spl.bin still can not boot.

**Comment by hno** [comment]
the sun4i branch should boot fine and do so both for me and others, but there is no output at all from SPL due to upstream console changes.

In wip/update I have adjusted console initialisation in ee6d3f93fea9bfca80d727ea485578ecdca611a5 to enable console output again, but it then crashes somehow. not yet identified how. Not even uart0_puts works which is strange.

limited amounts of uart0_puts do work if I do not include the change to enable spl console output. But also seem to hang if I try to output much data with uart0_puts. When it hangs no output at all is shown.

It's kind of like UART0 is not really running and only buffering data, and that something very late in the SPL process then kicks it running.
