### ISSUE TITLE
u-boot not working on a13-olinuxino

### ISSUE THREAD

**Issue by connetport** [linux-sunxi/u-boot-sunxi#52]
Hi,

Version of u-boot : 2013.10-rc2-08396-g6068143

The trouble is that it does not boot my compiled Linux.

Here is the output I have when trying to boot :

U-Boot SPL 2013.10-rc2-08396-g6068143 (Oct 05 2013 - 19:33:13)
Board: A13-OLinuXino
DRAM: 512 MiB
CPU: 1008000000Hz, AXI/AHB/APB: 3/2/2
spl: not an uImage at 1600
spl: not an uImage at 80
### ERROR ### Please RESET the board

Here is my procedure to build the sdcard :

-Purge the sdcard.
dd if=/dev/zero of=/dev/sdx bs=1M
-Creating the partition
one primary vfat from 2048 to 34815
one primary ext3 fills up the rest
-Formating the partitions
-Putting rootfs and modules to ext3
-Putting uImage and script.bin into the vfat
-dd if=spl/sunxi-spl.bin of=/dev/sdb bs=1024 seek=8
-dd if=u-boot.bin of=/dev/sdb bs=1024 seek=32

Every action on the sdcard is always followed by the sync command

**Comment by oliv3r** [comment]
On 10/06/13 09:26, connetport wrote:

> Hi,
> 
> Version of u-boot : 2013.10-rc2-08396-g6068143
> 
> The trouble is that it does not boot my compiled Linux.
> 
> Here is the output I have when trying to boot :
> 
> U-Boot SPL 2013.10-rc2-08396-g6068143 (Oct 05 2013 - 19:33:13)
> Board: A13-OLinuXino
> DRAM: 512 MiB
> CPU: 1008000000Hz, AXI/AHB/APB: 3/2/2
> spl: not an uImage at 1600
> spl: not an uImage at 80
> 
> ### ERROR ### Please RESET the board
> 
> Here is my procedure to build the sdcard :
> 
> -Purge the sdcard.
> dd if=/dev/zero of=/dev/sdx bs=1M
> -Creating the partition
> one primary vfat from 2048 to 34815
> one primary ext3 fills up the rest
> -Formating the partitions
> -Putting rootfs and modules to ext3
> -Putting uImage and script.bin into the vfat
> -dd if=spl/sunxi-spl.bin of=/dev/sdb bs=1024 seek=8
> -dd if=u-boot.bin of=/dev/sdb bs=1024 seek=32
> try using dd if=u-boot-sunxi-with-spl.bin of=/dev/sdb bs=1024 seek=8

though it seems your u-boot is somehow compiled incorrectly. what 
compiler etc are you using?

oliver

**Comment by connetport** [comment]
it worked. I now enter in kernel panic witch is something else.

I use : arm-linux-gnueabihf-gcc-4.6 under a debian wheezy 64bit

how is it incorrect ? Why do I differ from the normal compilation process ? What is spl ?

Best regards.

**Comment by connetport** [comment]
Maybe the trouble is this :
my make command is : make A13-OLinuXino CROSS_COMPILE=arm-linux-gnueabihf-

the command that is always seen in tutorials : "make a13-olinuxino CROSS_COMPILE=arm-linux-gnueabihf-" does not work, it gives me : 
make: **\* No rule to make target `a13-olinuxino_config)', needed by`a13-olinuxino'.  Stop.

Best regards.

**Comment by hno** [comment]
The first problem #ERROR please reset the board is because you used u-boot.bin instead of u-boot.img. Seee wiki.

Regarding the _config issue I beleive that is fixed now. Accidently made a typo in the top level Makefile some time ago when trying to fix a related issue.
