### ISSUE TITLE
mtd support a13

### ISSUE THREAD

**Issue by oldpenguin** [linux-sunxi/u-boot-sunxi#53]
Hello all
I would like to enable mtd support in a13-olinuxino platform.
From what I searched around, I have to define
CONFIG_CMD_MTDPARTS
CONFIG_MTD_DEVICE
MTDIDS_DEFAULT
MTDPARTS_DEFAULT
in file sun5i_a13.h
I have several questions:
1) Is mtd really supported on this platform ?
2) The a13 boot loader is expecting a FAT partition in the first nand blocks. How is it supposed to work if the whole flash is used as an mtd device ? Am I supposed to reserve a small portion of nand flash with FAT partitioning just for the boot loader ? Is this possible ?
Regards
António

**Comment by oliv3r** [comment]
u-boot sunxi in its current form does not support mtd yet. We have some experimental branches floating around, but this all still needs to be refined. So 1) no. 2) it's not, you have /dev/nanda which is only supported on the lichee branch of u-boot, e.g. the original allwinner u-boot driver and is thus not supported here.

You can boot from mmc or boot with the boot0/boot1/boot.axf/u-boot chain
