### ISSUE TITLE
mount rootfs fails unless rootdelay=1 added

### ISSUE THREAD

**Issue by garycramblitt** [linux-sunxi/u-boot-sunxi#6]
Building 4GB SD card following my own instructions at http://rhombus-tech.net/allwinner_a10/hacking_the_mele_a1000/Building_Debian_From_Source_Code_for_Mele/.  Unable to mount the root filesystem.  Here is boot log: http://pastebin.com/jWQYHaJP

Note that card present pin can be read immediately.

Tried with two different makes of 4GB SDHC cards.

This was working last week, BTW.

If I stop boot and add rootdelay, boots OK.

setenv root /dev/mmcblk0p2 rootdelay=1
saveenv
boot

**Comment by hno** [comment]
This is a kernel issue, not uboot.

Regards
Henrik

**Comment by garycramblitt** [comment]
Reported at https://github.com/amery/linux-allwinner

**Comment by hipboi** [comment]
rootwait should be better, because some sd card maybe slower. It's the
problem of the mmc driver, which was probed very late in the kernel.

On Mon, Jun 4, 2012 at 4:53 AM, garycramblitt <
reply@reply.github.com

> wrote:
> 
> Building 4GB SD card following my own instructions at
> http://rhombus-tech.net/allwinner_a10/hacking_the_mele_a1000/Building_Debian_From_Source_Code_for_Mele/.
>  Unable to mount the root filesystem.  Here is boot log:
> http://pastebin.com/jWQYHaJP
> 
> Note that card present pin can be read immediately.
> 
> Tried with two different makes of 4GB SDHC cards.
> 
> This was working last week, BTW.
> 
> If I stop boot and add rootdelay, boots OK.
> 
> setenv root /dev/mmcblk0p2 rootdelay=1
> saveenv
> boot
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hno/uboot-allwinner/issues/6

## 

Keep simple, stay foolish.
