### ISSUE TITLE
Unable to compile natively

### ISSUE THREAD

**Issue by mikkeloscar** [linux-sunxi/u-boot-sunxi#60]
I'm not able to build natively after 9b6e2c363f2686d6f7bf61fbe58b7591b71d3e8b because of this: https://github.com/linux-sunxi/u-boot-sunxi/blob/sunxi/arch/arm/config.mk#L8

It sets `CROSS_COMPILE = arm-linux-` if `$CROSS_COMPILE` is empty, which it is since I build on arm. Causing the build to look for `arm-linux-gcc` etc.

I don't know when this check is even useful because `CROSS_COMPILE` should be defined at this point if needed shouldn't it?

**Comment by oliv3r** [comment]
I think this is from upstream and thus you'd have to take it up with upstream. I've noticed the same when using the BSP, but simpyl passing CROSS_COMPILE= without anything after the =, makes it all work just fine.
