### ISSUE TITLE
The newest u-boot code doesn't boot on my BananaPi board

### ISSUE THREAD

**Issue by voiceshen** [linux-sunxi/u-boot-sunxi#62]
Hi,
  The newest u-boot code doesn't boot on my BananaPi (A20 based) board. The following is the log information.
--->8---
U-Boot SPL 2014.04-rc3-00706-g8611ddd (Apr 15 2014 - 22:18:25)
Board: bananapi
DRAM: 1024 MiB
CPU: 960000000Hz, AXI/AHB/APB: 3/2/2
MMC Device 0 not found
spl: mmc device not found!!
### ERROR ### Please RESET the board

---8<---

**Comment by ingmar-k** [comment]
I think I am seeing the same error on a A10 based BA_10_TV_BOX. Does not boot from sd card with u-boot built from the newest, current sources.
Will try older sources next.

**Comment by ingmar-k** [comment]
Ignore my previous comment, please!
The script that I had created some time ago used the wrong file, plus the wrong location.

In detail:
Previously it seems that "u-boot.BIN" was used and "seek=32". Now with the latest u-boot version it seems that it changed to "u-boot.IMG" and "seek=40". ;-)

Well, now it worked like a charm. SORRY!
