### ISSUE TITLE
Any u-boot-sunxi configuration for superpi?

### ISSUE THREAD

**Issue by jiapei100** [linux-sunxi/u-boot-sunxi#65]
Is there a u-boot configuration for superpi3 at http://superpi.org/ ?
Say, http://www.superpi.org/chanpin/superpi3/superpi3.htm ?

superpi3 is using a (A20 + Cortex A7 ) soc ...

That team seems to build Cubietruck, but, is there a u-boot configuration for such a superpi3?

Cheers
Pei

**Comment by jwrdegoede** [comment]
The superpi3 seems to be a 100% cubieboard2 clone, please use the cubieboard2 config.
