### ISSUE TITLE
SPL console output not working

### ISSUE THREAD

**Issue by hno** [linux-sunxi/u-boot-sunxi#7]
After the upgrade to v2012.04.01 SPL console output is not working at all.

Ouput wuth uart0_puts seems to work to some extent. But if console is enabled by setting gd->have_console = 1 then complete silence, even from uart0_puts sent earlier???

**Comment by hno** [comment]
see wip/update branch.

**Comment by hno** [comment]
make DEBUG=1

is needed to build that branch due to use of uart0_puts low level "early" print function.

**Comment by hno** [comment]
sön 2012-06-03 klockan 19:22 -0700 skrev jimyx17:

> HELLO! BOOT0 is starting!
> boot0 version : 1.2.1

this is a NAND boot using Allwinner standard bootloader, not u-boot SPL.

Regards
Henrik

**Comment by jimyx17** [comment]
Yep, I realized that I didn't dd the right device when I left the message so I deleted it... Sorry, my bad. I'll give it a try when I get home

**Comment by jimyx17** [comment]
This is what I've got... 

Connected.

U-Boot 2012.04.01-ge5c6594 (Jun 04 2012 - 21:48:06) Allwinner Technology 

CPU:   SUNXI Family
Board: A10-EVB
DRAM:  512 MiB
MMC:   SUNXI SD/MMC: 0
**\* Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Hit any key to stop autoboot:  0 
sun4i#version

U-Boot 2012.04.01-ge5c6594 (Jun 04 2012 - 21:48:06) Allwinner Technology 
arm-none-linux-gnueabi-gcc (Sourcery G++ Lite 2010.09-50) 4.5.1
GNU ld (Sourcery G++ Lite 2010.09-50) 2.20.51.20100809
sun4i#

**Comment by hno** [comment]
mån 2012-06-04 klockan 12:55 -0700 skrev jimyx17:

> This is what I've got... 
> 
> Connected.
> 
> U-Boot 2012.04.01-ge5c6594 (Jun 04 2012 - 21:48:06) Allwinner Technology 

Yes.. no output at all from SPL.

Compare to the output of the last known working SPL image and you'll
notice the difference.
http://www.henriknordstrom.net/code/A10/u-boot-mmc-hno-201203.img

Or wip/update branch and it will not work at all. There console output
is enabled [ee6d3f93fea9bfca80d727ea485578ecdca611a5], but something
hangs/crashes before the SPL can load u-boot.

Regards
Henrik

**Comment by jimyx17** [comment]
Look at this! if We add another puts call, the SPL is talking again...

```
diff --git a/arch/arm/cpu/armv7/sunxi/board.c b/arch/arm/cpu/armv7/sunxi/board.c
index a6dd431..b1446fd 100644
--- a/arch/arm/cpu/armv7/sunxi/board.c
+++ b/arch/arm/cpu/armv7/sunxi/board.c
@@ -188,6 +188,7 @@ void board_init_r(gd_t *id, ulong dest_addr)
        }

        puts("Jumping to U-Boot...\n");
+       puts("Working!\n");
        /* Jump to U-Boot image */
        uboot = (void *)CONFIG_SYS_TEXT_BASE;
        (*uboot)();
```

```
Connected.

Hello world

U-Boot SPL 2012.04.01-00004-gee6d3f9-dirty (Jun 08 2012 - 16:23:38)
MMC:   SUNXI SD/MMC: 0
Loading U-Boot...   OK!
Jumping to U-Boot...
Working!


U-Boot 2012.04.01-00004-gee6d3f9-dirty (Jun 08 2012 - 16:23:38) Allwinner Technology 

CPU:   SUNXI Family
Board: A10-EVB
DRAM:  512 MiB
MMC:   SUNXI SD/MMC: 0
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Hit any key to stop autoboot:  0 
sun4i#
```

I don't get the reason.....

**Comment by hno** [comment]
Fixed. The core issue was CONFIG_SPL_TEXT_BASE being wrong causing odd results and crashes.
