### ISSUE TITLE
bootcount on A20

### ISSUE THREAD

**Issue by davidjrme** [linux-sunxi/u-boot-sunxi#70]
Hello,
I'm trying to add the boot count limit functionality on an A20.
I added this two lines in sunxi-common.h:

```
#define CONFIG_BOOTCOUNT_LIMIT
#define CONFIG_BOOTCOUNT_ENV
```

and I set the bootlimit variable.
On boot I can see bootcount and bootlimit variables but if the linux boot fail, the bootcount isn't incremented.
Did you have an idea? What did I do wrong or miss?

**Comment by hno** [comment]
fre 2014-08-29 klockan 07:54 -0700 skrev davidjrme:

> I'm trying to add the boot count limit functionality on an A20.
> I added this two lines in sunxi-common.h:
> 
> #define CONFIG_BOOTCOUNT_LIMIT
> #define CONFIG_BOOTCOUNT_ENV
> 
> and I set the bootlimit variable.
> On boot I can see bootcount and bootlimit variables but if the linux
> boot fail, the bootcount isn't incremented.
> Did you have an idea? What did I do wrong or miss?

Have you set upgrade_available? (see README for CONFIG_BOOTCOUNT_ENV)

Regards
Henrik

**Comment by davidjrme** [comment]
Thanks to you! This works perfectly! I had forgot this variable...
