### ISSUE TITLE
Nand support

### ISSUE THREAD

**Issue by Philippe12** [linux-sunxi/u-boot-sunxi#84]
Hi
I try to add nand support on uboot.

But I have a question in uboot the nand is normally manage by mtd device but in kernel it manage by block.

Which will it be the best work : 
- to add under mtd for uboot and change the driver for kernel.
- to add like block device in uboot (that no standard) and don't change the nand driver in kernel.

**Comment by hno** [comment]
lör 2015-05-16 klockan 02:21 -0700 skrev Philippe FOUQUET:

> But I have a question in uboot the nand is normally manage by mtd
> device but in kernel it manage by block.

Allwinner have a block driver ontop of their nand, but normally NAND
drivers in the kernel is also MTD.

> Which will it be the best work : 
> 
> ```
>   * to add under mtd for uboot and change the driver for kernel.
> ```

Yes

Kernel & u-boot MTD drivers is in progress. First kernel version is
available mainline. But much help is needed if you are interested.

> ```
>   * to add like block device in uboot (that no standard) and don't
>     change the nand driver in kernel.
> ```

The Allwinner block NAND driver is a very odd beast, and is very
unlikely to get into mainline Linux or u-boot versions.

Regards
Henrik

**Comment by Philippe12** [comment]
It's great I worked on and driver on mtd I can read/write and in integer fast boot for android.
But it work in FEL mode.
I din't find where I must write in nand the SPL for booting?

**Comment by Philippe12** [comment]
How can i help you?

**Comment by hno** [comment]
tis 2015-05-26 klockan 05:20 -0700 skrev Philippe FOUQUET:

> How can i help you?

See mailinglist. Discussed a lot recently and a lot of progress is made.

Regards
Henrik

**Comment by Philippe12** [comment]
to old
