### ISSUE TITLE
Define DEBUG compile fails

### ISSUE THREAD

**Issue by microhobby** [linux-sunxi/u-boot-sunxi#96]
Can anyone help me with a doubt, why when I define DEBUG on file the compiler doesn't work?

`arm-linux-gnueabihf-ld.bfd: u-boot-spl section`.rodata' will not fit in region `.sram'
/home/matheus/Downloads/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ld.bfd: region`.sram' overflowed by 9612 bytes
scripts/Makefile.spl:291: recipe for target 'spl/u-boot-spl' failed
make[1]: **\* [spl/u-boot-spl] Error 1
Makefile:1343: recipe for target 'spl/u-boot-spl' failed
make: **\* [spl/u-boot-spl] Error 2`

**Comment by neithernut** [comment]
Without having a closer look: the space available for the boot-loader is quite restricted. Enabling debugging will naturally cause the binary to contain markers and other additional information. Hence, the executable code may end up being bigger than the section allocated for it, which pretty much is what your linker tries to tell you here.
